stages:
 - build

Ubuntu-master:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - export CMAKE_EXTRA_TARGETS="test"
  - export BUILD_GENERATOR="Unix Makefiles"
  - export GITHUB_MIRROR_URL="git@github.com:vg-lab/ShiFT"
  - bash .gitlabci.sh
 only:
  - master
 tags:
  - ubuntu

Ubuntu:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - export CMAKE_EXTRA_TARGETS="test"
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlabci.sh
 except:
  - master
 tags:
  - ubuntu


#OSX:
# stage: build
# script:
#  - date
#  - hostname
#  - uname -a
#  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
#  #- export CMAKE_EXTRA_TARGETS="test"
#  - export BUILD_GENERATOR="Unix Makefiles"
#  - bash .gitlabci.sh
# tags:
#  - osx-sierra

Win7-vs14:
 stage: build
 script:
  - call %ENVFILESDIR%\Boost-1.64-vs14-x64.bat
  - set CMAKE_EXTRA_TARGETS=RUN_TESTS
  - set RUN_TESTS=1
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set PATH=%PATH%;"c:\\Program Files\\Git\\bin"
  - set CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - bash.exe --login .gitlabci.sh
 tags:
  - win7
